import type { Question } from "@/entities/cbt";

export const questions : Question[] = [
    // ==================== 과목 1 (1 ~ 20) ====================
    {
        question_id: 1,
        certificate_id: 274,
        question_type_id: 1,
        text: "라우팅(Routing) 프로토콜이 아닌 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 1, question_id: 1, bool: false, content: " BGP", img: null },
            { answer_id: 2, question_id: 1, bool: false, content: " OSPF", img: null },
            { answer_id: 3, question_id: 1, bool: true, content: " SMTP", img: null },
            { answer_id: 4, question_id: 1, bool: false, content: " RIP", img: null },
        ],
    },
    {
        question_id: 2,
        certificate_id: 274,
        question_type_id: 1,
        text: "디렉터리 구조 중 중앙에 마스터 파일 디렉터리가 있고, 그 아래에 사용자별로 서로 다른 파일 디렉터리가 있는 구조는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 5, question_id: 2, bool: false, content: " 1단계 디렉터리 구조", img: null },
            { answer_id: 6, question_id: 2, bool: true, content: " 2단계 디렉터리 구조", img: null },
            { answer_id: 7, question_id: 2, bool: false, content: " 트리 디렉터리 구조", img: null },
            { answer_id: 8, question_id: 2, bool: false, content: " 비순환 그래프 디렉터리 구조", img: null },
        ],
    },
    {
        question_id: 3,
        certificate_id: 274,
        question_type_id: 1,
        text: "프로세스의 정의 중 틀린 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 9, question_id: 3, bool: true, content: " 동기적 행위를 일으키는 주체", img: null },
            { answer_id: 10, question_id: 3, bool: false, content: " 실행중인 프로그램", img: null },
            { answer_id: 11, question_id: 3, bool: false, content: " PCB를 가진 프로그램", img: null },
            { answer_id: 12, question_id: 3, bool: false, content: " 프로세서가 할당되는 실체", img: null },
        ],
    },
    {
        question_id: 4,
        certificate_id: 274,
        question_type_id: 1,
        text: "아키텍처 설계에서 뷰의 종류가 아닌 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 13, question_id: 4, bool: true, content: " 물리적 뷰", img: null },
            { answer_id: 14, question_id: 4, bool: false, content: " 논리적 뷰", img: null },
            { answer_id: 15, question_id: 4, bool: false, content: " 프로세스 뷰", img: null },
            { answer_id: 16, question_id: 4, bool: false, content: " 배포 뷰", img: null },
        ],
    },
    {
        question_id: 5,
        certificate_id: 274,
        question_type_id: 1,
        text: "사용자 인터페이스(User Interface)에 대한 설명으로 틀린 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 17, question_id: 5, bool: false, content: " 사용자와 시스템이 정보를 주고받는 상호 작용이 잘 이루어지도록 하는 장치나 소프트웨어를 의미한다.", img: null },
            { answer_id: 18, question_id: 5, bool: true, content: " 편리한 유지보수를 위해 개발자 중심으로 설계되어야 한다.", img: null },
            { answer_id: 19, question_id: 5, bool: false, content: " 배우기가 용이하고 쉽게 사용할 수 있도록 만들어져야 한다.", img: null },
            { answer_id: 20, question_id: 5, bool: false, content: " 사용자 요구사항이 UI에 반영될 수 있도록 구성해야 한다.", img: null },
        ],
    },
    {
        question_id: 6,
        certificate_id: 274,
        question_type_id: 1,
        text: "GoF(Gang of Four)의 디자인 패턴 중 데코레이터(Decorator)에 대한 설명으로 옳지 않은 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 21, question_id: 6, bool: false, content: " 구조 패턴에 속한다.", img: null },
            { answer_id: 22, question_id: 6, bool: true, content: " 호환성이 없는 클래스들의 인터페이스를 다른 클래스가 이용할 수 있도록 변환해준다.", img: null },
            { answer_id: 23, question_id: 6, bool: false, content: " 객체 간의 결합을 통해 동적으로 기능을 확장할 수 있다.", img: null },
            { answer_id: 24, question_id: 6, bool: false, content: " 임의의 객체에 부가적인 기능을 추가하기 위해 다른 객체들을 덧붙이는 방식으로 구현한다.", img: null },
        ],
    },
    {
        question_id: 7,
        certificate_id: 274,
        question_type_id: 1,
        text: "RR(Round Robin) 스케줄링에서 시간 할당량이 커질 경우 어떤 스케줄링과 같은 효과를 얻는가?",
        content: null,
        img: null,
        answers: [
            { answer_id: 25, question_id: 7, bool: false, content: " HRN", img: null },
            { answer_id: 26, question_id: 7, bool: true, content: " FCFS(FIFO)", img: null },
            { answer_id: 27, question_id: 7, bool: false, content: " SJF", img: null },
            { answer_id: 28, question_id: 7, bool: false, content: " SRT", img: null },
        ],
    },
    {
        question_id: 8,
        certificate_id: 274,
        question_type_id: 1,
        text: "FIFO 스케줄링에서 작업 도착 시간과 CPU 사용 시간은 다음 표와 같다. 모든 작업들의 평균 대기 시간은 얼마인가?",
        content: "작업 | 도착 시간 | CPU 사용시간\n----|---|---\n 1 | 0 | 4\n 2 | 1 | 10\n 3 | 4 | 1\n 4 | 8 | 7",
        img: null,
        answers: [
            { answer_id: 29, question_id: 8, bool: true, content: " 5", img: null },
            { answer_id: 30, question_id: 8, bool: false, content: " 5.5", img: null },
            { answer_id: 31, question_id: 8, bool: false, content: " 13.75", img: null },
            { answer_id: 32, question_id: 8, bool: false, content: " 3.25", img: null },
        ],
    },
    {
        question_id: 9,
        certificate_id: 274,
        question_type_id: 1,
        text: "소프트웨어 아키텍처 설계 시 고려사항이 아닌 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 33, question_id: 9, bool: false, content: " 개발자와 사용자의 의사소통 도구로 활용될 수 있어야 한다.", img: null },
            { answer_id: 34, question_id: 9, bool: false, content: " 이해하기 쉽고, 명확하게 작성해야 한다.", img: null },
            { answer_id: 35, question_id: 9, bool: true, content: " 재사용이 불가능하도록 설계해야 한다.", img: null },
            { answer_id: 36, question_id: 9, bool: false, content: " 이해 관계자들의 품질 요구사항을 반영하여 품질 속성을 결정한다.", img: null },
        ],
    },
    {
        question_id: 10,
        certificate_id: 274,
        question_type_id: 1,
        text: "다음 중 가장 결합도가 강한 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 37, question_id: 10, bool: false, content: " Data Coupling", img: null },
            { answer_id: 38, question_id: 10, bool: false, content: " Stamp Coupling", img: null },
            { answer_id: 39, question_id: 10, bool: true, content: " Content Coupling", img: null },
            { answer_id: 40, question_id: 10, bool: false, content: " Control Coupling", img: null },
        ],
    },
    {
        question_id: 11,
        certificate_id: 274,
        question_type_id: 1,
        text: "다음 중 빌드 자동화 도구가 아닌 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 41, question_id: 11, bool: true, content: " Fedora", img: null },
            { answer_id: 42, question_id: 11, bool: false, content: " Gradle", img: null },
            { answer_id: 43, question_id: 11, bool: false, content: " Jenkins", img: null },
            { answer_id: 44, question_id: 11, bool: false, content: " Maven", img: null },
        ],
    },
    {
        question_id: 12,
        certificate_id: 274,
        question_type_id: 1,
        text: "UNIX 시스템에서 파일의 권한 모드 설정에 관한 명령어는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 45, question_id: 12, bool: true, content: " chmod", img: null },
            { answer_id: 46, question_id: 12, bool: false, content: " cp", img: null },
            { answer_id: 47, question_id: 12, bool: false, content: " ls", img: null },
            { answer_id: 48, question_id: 12, bool: false, content: " chown", img: null },
        ],
    },
    {
        question_id: 13,
        certificate_id: 274,
        question_type_id: 1,
        text: "소프트웨어의 개발 과정에서 소프트웨어의 변경 사항을 관리하기 위해 개발된 일련의 활동은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 49, question_id: 13, bool: false, content: " 정규화", img: null },
            { answer_id: 50, question_id: 13, bool: false, content: " 프로토타입", img: null },
            { answer_id: 51, question_id: 13, bool: false, content: " 통합 테스트", img: null },
            { answer_id: 52, question_id: 13, bool: true, content: " 형상 관리", img: null },
        ],
    },
    {
        question_id: 14,
        certificate_id: 274,
        question_type_id: 1,
        text: "LAN의 한 종류인 100Base-T 네트워크에서 사용되는 전송 매체는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 53, question_id: 14, bool: false, content: " Coaxial cable", img: null },
            { answer_id: 54, question_id: 14, bool: false, content: " Optical cable", img: null },
            { answer_id: 55, question_id: 14, bool: true, content: " UTP cable", img: null },
            { answer_id: 56, question_id: 14, bool: false, content: " Microwave cable", img: null },
        ],
    },
    {
        question_id: 15,
        certificate_id: 274,
        question_type_id: 1,
        text: "연산 P, V와 정수 변수를 이용하여 동기화 문제를 해결하는 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 57, question_id: 15, bool: false, content: " Critical Section", img: null },
            { answer_id: 58, question_id: 15, bool: false, content: " Monitor", img: null },
            { answer_id: 59, question_id: 15, bool: true, content: " Semaphore", img: null },
            { answer_id: 60, question_id: 15, bool: false, content: " Mutual Exclusion", img: null },
        ],
    },
    {
        question_id: 16,
        certificate_id: 274,
        question_type_id: 1,
        text: "파이프 필터 형태의 소프트웨어 아키텍처에 대한 설명으로 옳은 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 61, question_id: 16, bool: false, content: " 노드와 간선으로 구성된다.", img: null },
            { answer_id: 62, question_id: 16, bool: false, content: " 계층 모델이라고도 한다.", img: null },
            { answer_id: 63, question_id: 16, bool: true, content: " 서브 시스템이 입력 데이터를 받아 처리하고 결과를 다음 서브 시스템으로 넘겨주는 과정을 반복한다.", img: null },
            { answer_id: 64, question_id: 16, bool: false, content: " 3개의 서브 시스템(모델, 뷰, 제어)으로 구성되어 있다.", img: null },
        ],
    },
    {
        question_id: 17,
        certificate_id: 274,
        question_type_id: 1,
        text: "다음 설명에 해당하는 용어는?",
        content: "소프트웨어의 구현 단계에서 발생할 수 있는 보안 취약점들을 최소화하기 위해 보안 요소들을 고려하며 코딩하는 것을 의미하며, 보안 취약점들을 사전에 대응하여 안정성과 신뢰성을 확보하기 위해 사용된다.",
        img: null,
        answers: [
            { answer_id: 65, question_id: 17, bool: false, content: " SDLC", img: null },
            { answer_id: 66, question_id: 17, bool: true, content: " Secure Coding", img: null },
            { answer_id: 67, question_id: 17, bool: false, content: " CLASP", img: null },
            { answer_id: 68, question_id: 17, bool: false, content: " OWASP", img: null },
        ],
    },
    {
        question_id: 18,
        certificate_id: 274,
        question_type_id: 1,
        text: "데이터 전송 방식 중 패킷 교환 방식에 대한 설명으로 틀린 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 69, question_id: 18, bool: false, content: " 가상 회선 방식과 데이터그램 방식이 있다.", img: null },
            { answer_id: 70, question_id: 18, bool: false, content: " 전송에 실패한 패킷의 경우 재전송이 가능하다.", img: null },
            { answer_id: 71, question_id: 18, bool: false, content: " 패킷 단위로 헤더를 추가하므로 패킷별 오버헤드가 발생한다.", img: null },
            { answer_id: 72, question_id: 18, bool: true, content: " 실시간 전송이나 대량의 데이터 전송에 적합하다.", img: null },
        ],
    },
    {
        question_id: 19,
        certificate_id: 274,
        question_type_id: 1,
        text: "자원 보호 기법 중 접근 제어 행렬에서 수행할 수 있는 각 행렬들을 따른 것으로서 각 영역에 대한 권한은 객체의 그 객체에 허용된 연산자로 구성되는 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 73, question_id: 19, bool: false, content: " Global Table", img: null },
            { answer_id: 74, question_id: 19, bool: false, content: " Access Control List", img: null },
            { answer_id: 75, question_id: 19, bool: true, content: " Capability List", img: null },
            { answer_id: 76, question_id: 19, bool: false, content: " Lock/Key", img: null },
        ],
    },
    {
        question_id: 20,
        certificate_id: 274,
        question_type_id: 1,
        text: "가상기억장치에 대한 설명으로 옳지 않은 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 77, question_id: 20, bool: false, content: " 기억공간의 확장을 위한 것이다.", img: null },
            { answer_id: 78, question_id: 20, bool: false, content: " 주소 변환 작업이 필요하다.", img: null },
            { answer_id: 79, question_id: 20, bool: false, content: " 소프트웨어적인 방법이다.", img: null },
            { answer_id: 80, question_id: 20, bool: true, content: " 주기억장치를 보조기억장치처럼 사용한다.", img: null },
        ],
    },
    // ==================== 과목 2 (21 ~ 40) ====================
    {
        question_id: 21,
        certificate_id: 274,
        question_type_id: 2,
        text: "다음은 아이디와 암호를 입력하는 로그인 창을 JavaScript로 구현한 것이다. 괄호(㉠~㉢)에 들어갈 적합한 속성은?",
        content: "<body>\n  <html>\n    <p>아이디<input type=\"text\" name=\"id\"></p>\n    <p>패스워드<input type=\"password\" name=\"pw\"></p>\n    <㉠ ㉡=\"post( )\" ㉢=\"log01.jsp\">\n  </html>\n</body>",
        img: null,
        answers: [
            { answer_id: 81, question_id: 21, bool: false, content: " form, action, method, form", img: null },
            { answer_id: 82, question_id: 21, bool: true, content: " form, method, action, form", img: null },
            { answer_id: 83, question_id: 21, bool: false, content: " function, form, method, function", img: null },
            { answer_id: 84, question_id: 21, bool: false, content: " function, action, form, function", img: null },
        ],
    },
    {
        question_id: 22,
        certificate_id: 274,
        question_type_id: 2,
        text: "특정 모듈에 대해서 존재하는 처리 요소들 간의 기능적 연관성을 의미하는 것으로 모듈이나 여러 처리 같은 유사한 기능을 행하는 요소처리 하나의 요소로 묶는 응집도는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 85, question_id: 22, bool: false, content: " 순환적 응집도", img: null },
            { answer_id: 86, question_id: 22, bool: true, content: " 논리적 응집도", img: null },
            { answer_id: 87, question_id: 22, bool: false, content: " 순차적 응집도", img: null },
            { answer_id: 88, question_id: 22, bool: false, content: " 절차적 응집도", img: null },
        ],
    },
    {
        question_id: 23,
        certificate_id: 274,
        question_type_id: 2,
        text: "다음 중 가장 결합도가 강한 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 89, question_id: 23, bool: false, content: " Data Coupling", img: null },
            { answer_id: 90, question_id: 23, bool: false, content: " Stamp Coupling", img: null },
            { answer_id: 91, question_id: 23, bool: true, content: " Content Coupling", img: null },
            { answer_id: 92, question_id: 23, bool: false, content: " Control Coupling", img: null },
        ],
    },
    {
        question_id: 24,
        certificate_id: 274,
        question_type_id: 2,
        text: "C언어에서 상수를 정의할 때 사용하는 예약어는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 93, question_id: 24, bool: false, content: " #include", img: null },
            { answer_id: 94, question_id: 24, bool: true, content: " #define", img: null },
            { answer_id: 95, question_id: 24, bool: false, content: " #value", img: null },
            { answer_id: 96, question_id: 24, bool: false, content: " #function", img: null },
        ],
    },
    {
        question_id: 25,
        certificate_id: 274,
        question_type_id: 2,
        text: "외부 변수(External Variable)에 대한 설명으로 옳지 않은 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 97, question_id: 25, bool: false, content: " 외부 변수는 함수 밖에서 선언한다.", img: null },
            { answer_id: 98, question_id: 25, bool: false, content: " 초기화하지 않으면 자동으로 0으로 초기화된다.", img: null },
            { answer_id: 99, question_id: 25, bool: true, content: " 함수가 종료되면 값도 소멸된다.", img: null },
            { answer_id: 100, question_id: 25, bool: false, content: " 다른 파일에서 선언된 변수를 참조할 경우 초기화할 수 없다.", img: null },
        ],
    },
    {
        question_id: 26,
        certificate_id: 274,
        question_type_id: 2,
        text: "다음은 1000까지의 7의 배수를 모두 합하는 JavaScript 코드이다. 괄호(㉠, ㉡)에 들어갈 알맞은 예약어는?",
        content: "<script>\n  var r=0, i = 0;\n  ㉠ ( i ) {\n    if (i%7 == 0) {\n      r = r + i;\n    }\n  } ㉡ ( i < 1000);\n  console.log(r);\n</script>",
        img: null,
        answers: [
            { answer_id: 101, question_id: 26, bool: true, content: " do-while", img: null },
            { answer_id: 102, question_id: 26, bool: false, content: " do-loop", img: null },
            { answer_id: 103, question_id: 26, bool: false, content: " while-do", img: null },
            { answer_id: 104, question_id: 26, bool: false, content: " loop-do", img: null },
        ],
    },
    {
        question_id: 27,
        certificate_id: 274,
        question_type_id: 2,
        text: "자바스크립트에서 배열에 데이터를 입력하고자 할 때 사용하는 메소드는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 105, question_id: 27, bool: true, content: " push", img: null },
            { answer_id: 106, question_id: 27, bool: false, content: " add", img: null },
            { answer_id: 107, question_id: 27, bool: false, content: " pop", img: null },
            { answer_id: 108, question_id: 27, bool: false, content: " shift", img: null },
        ],
    },
    {
        question_id: 28,
        certificate_id: 274,
        question_type_id: 2,
        text: "다음과 같이 HTML 문서를 작성했을 때 노란색 배경을 갖는 셀의 위치는?",
        content: "<html>\n  <style>\n    tr:nth-child(even) { background-color:yellow; }\n  </style>\n  <body>\n    <table>\n      <tr>\n        <th></th>\n      </tr>\n      <tr>\n        <td></td>\n      </tr>\n      <tr>\n        <td></td>\n      </tr>\n      <tr>\n        <td></td>\n      </tr>\n    </table>\n  </body>\n</html>",
        img: null,
        answers: [
            { answer_id: 109, question_id: 28, bool: false, content: " 1행", img: null },
            { answer_id: 110, question_id: 28, bool: false, content: " 2행", img: null },
            { answer_id: 111, question_id: 28, bool: true, content: " 3행", img: null },
            { answer_id: 112, question_id: 28, bool: false, content: " 4행", img: null },
        ],
    },
    {
        question_id: 29,
        certificate_id: 274,
        question_type_id: 2,
        text: "다음 중 C 언어에서 수학 함수를 사용하기 위해 추가해야 하는 라이브러리는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 113, question_id: 29, bool: false, content: " stdio.h", img: null },
            { answer_id: 114, question_id: 29, bool: true, content: " math.h", img: null },
            { answer_id: 115, question_id: 29, bool: false, content: " stdlib.h", img: null },
            { answer_id: 116, question_id: 29, bool: false, content: " time.h", img: null },
        ],
    },
    {
        question_id: 30,
        certificate_id: 274,
        question_type_id: 2,
        text: "객체지향의 주요 개념에 대한 설명으로 틀린 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 117, question_id: 30, bool: true, content: " 캡슐화는 상위 클래스에서 속성이나 연산을 전달받아 새로운 형태의 클래스로 확장하여 사용하는 것을 의미한다.", img: null },
            { answer_id: 118, question_id: 30, bool: false, content: " 클래스는 실제 세계에 존재하거나 생각할 수 있는 것을 말한다.", img: null },
            { answer_id: 119, question_id: 30, bool: false, content: " 트랜잭션은 하나 이상의 유사한 객체들을 묶어 공통된 특성을 표현한 것이다.", img: null },
            { answer_id: 120, question_id: 30, bool: false, content: " 다형성은 상속받은 여러 개의 하위 객체들이 다른 형태의 특성을 갖는 객체로 이용될 수 있는 성질이다.", img: null },
        ],
    },
    {
        question_id: 31,
        certificate_id: 274,
        question_type_id: 2,
        text: "바람직한 소프트웨어 설계 지침이 아닌 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 121, question_id: 31, bool: false, content: " 적당한 모듈의 크기를 유지한다.", img: null },
            { answer_id: 122, question_id: 31, bool: false, content: " 오늘 끝낼 일을 설계 문서를 분석하여 복잡도와 중복을 줄인다.", img: null },
            { answer_id: 123, question_id: 31, bool: true, content: " 모듈 간의 결합도는 강할수록 바람직하다.", img: null },
            { answer_id: 124, question_id: 31, bool: false, content: " 모듈 안의 응집적인 체계를 위해 설계에서 계층적 자료 조직이 제시되어야 한다.", img: null },
        ],
    },
    {
        question_id: 32,
        certificate_id: 274,
        question_type_id: 2,
        text: "추상 클래스에 대한 설명으로 틀린 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 125, question_id: 32, bool: false, content: " 자식 클래스에서 구현하려는 기능들의 공통점만을 모은 것이다.", img: null },
            { answer_id: 126, question_id: 32, bool: false, content: " 인스턴스 생성이 불가능하다.", img: null },
            { answer_id: 127, question_id: 32, bool: true, content: " 부모 클래스에서 상속받아 구체화한다.", img: null },
            { answer_id: 128, question_id: 32, bool: false, content: " 자식 클래스의 인스턴스를 생성하는 방식으로 사용한다.", img: null },
        ],
    },
    {
        question_id: 33,
        certificate_id: 274,
        question_type_id: 2,
        text: "JavaScript에서 다음 그림과 같은 창을 띄우기 위해 사용한 명령어로 옳은 것은?",
        content: "이미지에 '이 페이지 내용'이라는 제목과 'title'이라는 텍스트, 'default'가 입력된 프롬프트 창이 표시되어 있습니다.",
        img: null,
        answers: [
            { answer_id: 129, question_id: 33, bool: false, content: " alert(\"title\", \"default\")", img: null },
            { answer_id: 130, question_id: 33, bool: true, content: " prompt(\"title\", \"default\")", img: null },
            { answer_id: 131, question_id: 33, bool: false, content: " alert(\"default\", \"title\")", img: null },
            { answer_id: 132, question_id: 33, bool: false, content: " prompt(\"default\", \"title\")", img: null },
        ],
    },
    {
        question_id: 34,
        certificate_id: 274,
        question_type_id: 2,
        text: "모듈을 설계하기 위해서 바람직한 응집도(Cohesion)와 결합도(Coupling)의 관계는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 133, question_id: 34, bool: false, content: " 응집도는 약하고 결합도는 강해야 한다.", img: null },
            { answer_id: 134, question_id: 34, bool: true, content: " 응집도는 강하고 결합도는 약해야 한다.", img: null },
            { answer_id: 135, question_id: 34, bool: false, content: " 응집도를 약하고 결합도도 약해야 한다.", img: null },
            { answer_id: 136, question_id: 34, bool: false, content: " 응집도도 강하고 결합도도 강해야 한다.", img: null },
        ],
    },
    {
        question_id: 35,
        certificate_id: 274,
        question_type_id: 2,
        text: "다음 자바 프로그램 조건문에 대해 삼항 조건 연산자를 사용하여 옳게 나타낸 것은?",
        content: "if (a > b) {\n  max = a;\n} else if (a < b) {\n  max = b;\n}",
        img: null,
        answers: [
            { answer_id: 137, question_id: 35, bool: true, content: " max = (a > b) ? a : b;", img: null },
            { answer_id: 138, question_id: 35, bool: false, content: " (a > b) ? max = a : max = b;", img: null },
            { answer_id: 139, question_id: 35, bool: false, content: " max = (a < b) ? a : b;", img: null },
            { answer_id: 140, question_id: 35, bool: false, content: " (a < b) ? max = a : max = b;", img: null },
        ],
    },
    {
        question_id: 36,
        certificate_id: 274,
        question_type_id: 2,
        text: "다음 중 C언어에서 변수명으로 사용할 수 있는 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 141, question_id: 36, bool: false, content: " 8_dei", img: null },
            { answer_id: 142, question_id: 36, bool: false, content: " while", img: null },
            { answer_id: 143, question_id: 36, bool: false, content: " di sum", img: null },
            { answer_id: 144, question_id: 36, bool: true, content: " lAvg", img: null },
        ],
    },
    {
        question_id: 37,
        certificate_id: 274,
        question_type_id: 2,
        text: "정보 보안의 3대 요소에 해당하지 않는 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 145, question_id: 37, bool: true, content: " 위변성", img: null },
            { answer_id: 146, question_id: 37, bool: false, content: " 가용성", img: null },
            { answer_id: 147, question_id: 37, bool: false, content: " 무결성", img: null },
            { answer_id: 148, question_id: 37, bool: false, content: " 기밀성", img: null },
        ],
    },
    {
        question_id: 38,
        certificate_id: 274,
        question_type_id: 2,
        text: "C언어에서 정수 변수 a, b에 각각 1, 2가 저장되어 있을 때 다음 식의 연산 결과로 옳은 것은?",
        content: "a < b + 2 && a << 1 == b",
        img: null,
        answers: [
            { answer_id: 149, question_id: 38, bool: false, content: " 0", img: null },
            { answer_id: 150, question_id: 38, bool: true, content: " 1", img: null },
            { answer_id: 151, question_id: 38, bool: false, content: " 3", img: null },
            { answer_id: 152, question_id: 38, bool: false, content: " 5", img: null },
        ],
    },
    {
        question_id: 39,
        certificate_id: 274,
        question_type_id: 2,
        text: "특정 모듈에 대해서 존재하는 처리 요소들 간의 기능적 연관성을 의미하는 것으로 입력이나 여러 처리 같은 유사한 기능을 행하는 요소끼리 하나의 요소로 묶는 응집도는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 153, question_id: 39, bool: false, content: " 기능적 응집도", img: null },
            { answer_id: 154, question_id: 39, bool: false, content: " 순차적 응집도", img: null },
            { answer_id: 155, question_id: 39, bool: true, content: " 논리적 응집도", img: null },
            { answer_id: 156, question_id: 39, bool: false, content: " 절차적 응집도", img: null },
        ],
    },
    {
        question_id: 40,
        certificate_id: 274,
        question_type_id: 2,
        text: "스크립트 언어가 아닌 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 157, question_id: 40, bool: false, content: " PHP", img: null },
            { answer_id: 158, question_id: 40, bool: true, content: " Cobol", img: null },
            { answer_id: 159, question_id: 40, bool: false, content: " Basic", img: null },
            { answer_id: 160, question_id: 40, bool: false, content: " Python", img: null },
        ],
    },
    // ==================== 과목 3 (41 ~ 60) ====================
    {
        question_id: 41,
        certificate_id: 274,
        question_type_id: 3,
        text: "SQL의 데이터 조작문(DML)에 해당하는 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 161, question_id: 41, bool: false, content: " CREATE", img: null },
            { answer_id: 162, question_id: 41, bool: true, content: " INSERT", img: null },
            { answer_id: 163, question_id: 41, bool: false, content: " ALTER", img: null },
            { answer_id: 164, question_id: 41, bool: false, content: " DROP", img: null },
        ],
    },
    {
        question_id: 42,
        certificate_id: 274,
        question_type_id: 3,
        text: "다음 중 교차곱을 의미하는 기호는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 165, question_id: 42, bool: false, content: " U", img: null },
            { answer_id: 166, question_id: 42, bool: false, content: " ∩", img: null },
            { answer_id: 167, question_id: 42, bool: false, content: " -", img: null },
            { answer_id: 168, question_id: 42, bool: true, content: " ×", img: null },
        ],
    },
    {
        question_id: 43,
        certificate_id: 274,
        question_type_id: 3,
        text: "A → B 이고 B → C 일 때 A → C를 만족하는 종속 관계를 제거하는 정규화 단계는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 169, question_id: 43, bool: false, content: " 1NF → 2NF", img: null },
            { answer_id: 170, question_id: 43, bool: true, content: " 2NF → 3NF", img: null },
            { answer_id: 171, question_id: 43, bool: false, content: " 3NF → BCNF", img: null },
            { answer_id: 172, question_id: 43, bool: false, content: " 비정규 릴레이션 → 1NF", img: null },
        ],
    },
    {
        question_id: 44,
        certificate_id: 274,
        question_type_id: 3,
        text: "데이터베이스에서 두 릴레이션을 합병할 때 사용하는 연산자는?",
        content: null,
        img: null,
        answers: [
            { answer_id: 173, question_id: 44, bool: true, content: " 결합 연산자", img: null },
            { answer_id: 174, question_id: 44, bool: false, content: " 관계 연산자", img: null },
            { answer_id: 175, question_id: 44, bool: false, content: " 비교 연산자", img: null },
            { answer_id: 176, question_id: 44, bool: false, content: " 논리 연산자", img: null },
        ],
    },
    {
        question_id: 45,
        certificate_id: 274,
        question_type_id: 3,
        text: "'컴퓨터공학과'이면서 3학년인 학생의 이름만 조회하는 SQL문으로 올바른 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 177, question_id: 45, bool: true, content: " SELECT 이름 FROM 학생 WHERE 학년 = 3 AND 학과 = “컴퓨터공학”", img: null },
            { answer_id: 178, question_id: 45, bool: false, content: " SELECT 이름 FROM 학생 WHERE 학년 = 3 OR 학과 = “컴퓨터공학”", img: null },
            { answer_id: 179, question_id: 45, bool: false, content: " SELECT 이름 WHEN 학생 WHERE 학년 = 3 AND 학과 = “컴퓨터공학”", img: null },
            { answer_id: 180, question_id: 45, bool: false, content: " SELECT 이름 WHEN 학생 WHERE 학년 = 3 OR 학과 = “컴퓨터공학”", img: null },
        ],
    },
    {
        question_id: 46,
        certificate_id: 274,
        question_type_id: 3,
        text: "관계대수와 관계해석에 대한 설명으로 옳지 않은 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 181, question_id: 46, bool: false, content: " 기본적으로 관계대수와 관계해석은 관계 데이터베이스를 처리하는 기능과 능력면에서 동등하다.", img: null },
            { answer_id: 182, question_id: 46, bool: true, content: " 관계대수는 질의에 대한 해를 생성하기 위해 수행해야 할 연산의 순서를 명시해야 하므로 비절차적 특성을 가진다.", img: null },
            { answer_id: 183, question_id: 46, bool: false, content: " 관계해석은 원하는 정보가 무엇이라는 것만 정의하는 비절차적 특성을 가지고 있다.", img: null },
            { answer_id: 184, question_id: 46, bool: false, content: " 관계해석은 수학의 프레디컷 해석(Predicate Calculus)에 기반을 두고 있다.", img: null },
        ],
    },
    {
        question_id: 47,
        certificate_id: 274,
        question_type_id: 3,
        text: "SQL 명령어 중 DDL에 해당하는 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 185, question_id: 47, bool: false, content: " SELECT", img: null },
            { answer_id: 186, question_id: 47, bool: false, content: " UPDATE", img: null },
            { answer_id: 187, question_id: 47, bool: false, content: " DELETE", img: null },
            { answer_id: 188, question_id: 47, bool: true, content: " ALTER", img: null },
        ],
    },
    {
        question_id: 48,
        certificate_id: 274,
        question_type_id: 3,
        text: "한 릴레이션의 기본키를 구성하는 어떠한 속성 값도 널(Null) 값이거나 중복 값을 가질 수 없다는 것을 의미하는 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 189, question_id: 48, bool: true, content: " 개체 무결성 제약 조건", img: null },
            { answer_id: 190, question_id: 48, bool: false, content: " 참조 무결성 제약 조건", img: null },
            { answer_id: 191, question_id: 48, bool: false, content: " 도메인 무결성 제약 조건", img: null },
            { answer_id: 192, question_id: 48, bool: false, content: " 키 무결성 제약 조건", img: null },
        ],
    },
    {
        question_id: 49,
        certificate_id: 274,
        question_type_id: 3,
        text: "릴레이션에 속성을 조작할 때 데이터의 중복으로 인하여 발생하는 이상(Anomaly) 현상이 아닌 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 193, question_id: 49, bool: true, content: " 검색 이상", img: null },
            { answer_id: 194, question_id: 49, bool: false, content: " 삽입 이상", img: null },
            { answer_id: 195, question_id: 49, bool: false, content: " 삭제 이상", img: null },
            { answer_id: 196, question_id: 49, bool: false, content: " 갱신 이상", img: null },
        ],
    },
    {
        question_id: 50,
        certificate_id: 274,
        question_type_id: 3,
        text: "키는 개체 집합에서 고유하게 튜플을 식별할 수 있는 속성이다. 데이터베이스에서 사용하는 키의 종류에 대한 설명 중 옳지 않은 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 197, question_id: 50, bool: false, content: " 후보키는 튜플들을 고유하게 식별할 수 있는 속성이다.", img: null },
            { answer_id: 198, question_id: 50, bool: false, content: " 슈퍼키는 한 릴레이션 내의 속성들의 집합으로 구성된 키이다.", img: null },
            { answer_id: 199, question_id: 50, bool: false, content: " 외래키는 다른 릴레이션의 기본키를 참조하는 속성 또는 속성들의 집합이다.", img: null },
            { answer_id: 200, question_id: 50, bool: true, content: " 보조키는 후보키 중에서 대표로 선정된 키이다.", img: null },
        ],
    },
    {
        question_id: 51,
        certificate_id: 274,
        question_type_id: 3,
        text: "SQL에서 VIEW를 삭제할 때 사용하는 명령은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 201, question_id: 51, bool: false, content: " ERASE", img: null },
            { answer_id: 202, question_id: 51, bool: false, content: " KILL", img: null },
            { answer_id: 203, question_id: 51, bool: true, content: " DROP", img: null },
            { answer_id: 204, question_id: 51, bool: false, content: " DELETE", img: null },
        ],
    },
    {
        question_id: 52,
        certificate_id: 274,
        question_type_id: 3,
        text: "해싱에서 서로 다른 두 개 이상의 레코드가 동일한 주소를 갖는 현상을 의미하는 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 205, question_id: 52, bool: false, content: " Synonym", img: null },
            { answer_id: 206, question_id: 52, bool: true, content: " Collision", img: null },
            { answer_id: 207, question_id: 52, bool: false, content: " Bucket", img: null },
            { answer_id: 208, question_id: 52, bool: false, content: " Slot", img: null },
        ],
    },
    {
        question_id: 53,
        certificate_id: 274,
        question_type_id: 3,
        text: "시스템 카탈로그에 대한 설명으로 틀린 것은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 209, question_id: 53, bool: false, content: " 시스템 자신이 필요로 하는 스키마 및 여러 가지 객체에 관한 정보를 포함하고 있는 시스템 데이터베이스이다.", img: null },
            { answer_id: 210, question_id: 53, bool: false, content: " 사용자는 SQL을 이용하여 카탈로그의 내용을 검색할 수 있다.", img: null },
            { answer_id: 211, question_id: 53, bool: false, content: " 데이터 사전이라고도 한다.", img: null },
            { answer_id: 212, question_id: 53, bool: true, content: " 일반 사용자는 시스템 테이블의 내용을 갱신할 수 없다.", img: null },
        ],
    },
    {
        question_id: 54,
        certificate_id: 274,
        question_type_id: 3,
        text: "버블 정렬을 이용한 오름차순 정렬시 다음 자료에 대한 3회전 후의 결과는?",
        content: "9, 6, 7, 3, 5",
        img: null,
        answers: [
            { answer_id: 213, question_id: 54, bool: true, content: " 3, 5, 6, 7, 9", img: null },
            { answer_id: 214, question_id: 54, bool: false, content: " 6, 3, 5, 7, 9", img: null },
            { answer_id: 215, question_id: 54, bool: false, content: " 6, 7, 3, 5, 9", img: null },
            { answer_id: 216, question_id: 54, bool: false, content: " 3, 7, 6, 5, 9", img: null },
        ],
    },
    {
        question_id: 55,
        certificate_id: 274,
        question_type_id: 3,
        text: "데이터베이스에서 아직 알려지지 않거나 모르는 값으로서 '해당 없음' 등의 이유로 유효한 부재를 나타내기 위해 사용하는 특수한 데이터 값은 무엇인가?",
        content: null,
        img: null,
        answers: [
            { answer_id: 217, question_id: 55, bool: false, content: " 원자값(Atomic Value)", img: null },
            { answer_id: 218, question_id: 55, bool: false, content: " 참조값(Reference Value)", img: null },
            { answer_id: 219, question_id: 55, bool: false, content: " 무결성(Integrity Value)", img: null },
            { answer_id: 220, question_id: 55, bool: true, content: " 널 값(Null Value)", img: null },
        ],
    },
    {
        question_id: 56,
        certificate_id: 274,
        question_type_id: 3,
        text: "아래 SQL 문에서 WHERE 절의 조건이 의미하는 것은?",
        content: "SELECT 이름, 과목, 점수\nFROM 학생\nWHERE 이름 NOT LIKE '박__';",
        img: null,
        answers: [
            { answer_id: 221, question_id: 56, bool: false, content: " '박'으로 시작되는 모든 문자 이름을 검색한다.", img: null },
            { answer_id: 222, question_id: 56, bool: false, content: " '박'으로 시작하지 않는 모든 문자 이름을 검색한다.", img: null },
            { answer_id: 223, question_id: 56, bool: false, content: " '박'으로 시작하는 3글자의 문자 이름을 검색한다.", img: null },
            { answer_id: 224, question_id: 56, bool: true, content: " '박'으로 시작하지 않는 3글자의 문자 이름을 검색한다.", img: null },
        ],
    },
    {
        question_id: 57,
        certificate_id: 274,
        question_type_id: 3,
        text: "개체-관계 모델의 E-R 다이어그램에서 속성을 의미하는 그래픽 표현은?",
        content: null,
        img: null,
        answers: [
            { answer_id: 225, question_id: 57, bool: false, content: " 사각형", img: null },
            { answer_id: 226, question_id: 57, bool: true, content: " 타원", img: null },
            { answer_id: 227, question_id: 57, bool: false, content: " 마름모", img: null },
            { answer_id: 228, question_id: 57, bool: false, content: " 삼각형", img: null },
        ],
    },
    {
        question_id: 58,
        certificate_id: 274,
        question_type_id: 3,
        text: "다음 질의문 실행의 결과는?",
        content: "SELECT 가격 FROM 도서가격 WHERE 책번호 = (SELECT 책번호 FROM 도서 WHERE 책명 = '운영체제');\n\n<도서>\n책번호 | 책명\n---|---\n1111 | 운영체제\n2222 | 세계지도\n3333 | 생활영어\n\n<도서가격>\n책번호 | 가격\n---|---\n1111 | 15000\n2222 | 23000\n3333 | 7000\n4444 | 5000",
        img: null,
        answers: [
            { answer_id: 229, question_id: 58, bool: false, content: " 5000", img: null },
            { answer_id: 230, question_id: 58, bool: false, content: " 7000", img: null },
            { answer_id: 231, question_id: 58, bool: true, content: " 15000", img: null },
            { answer_id: 232, question_id: 58, bool: false, content: " 23000", img: null },
        ],
    },
    {
        question_id: 59,
        certificate_id: 274,
        question_type_id: 3,
        text: "다음에 해당하는 트랜잭션(ACID)의 특성은?",
        content: "둘 이상의 트랜잭션이 동시에 병행 실행되는 경우 어느 하나의 트랜잭션 실행 중에 다른 트랜잭션의 연산이 끼어들 수 없다.",
        img: null,
        answers: [
            { answer_id: 233, question_id: 59, bool: false, content: " Atomicity", img: null },
            { answer_id: 234, question_id: 59, bool: false, content: " Consistency", img: null },
            { answer_id: 235, question_id: 59, bool: true, content: " Isolation", img: null },
            { answer_id: 236, question_id: 59, bool: false, content: " Durability", img: null },
        ],
    },
    {
        question_id: 60,
        certificate_id: 274,
        question_type_id: 3,
        text: "다음 설명이 의미하는 것은?",
        content: "• 삽입과 삭제가 리스트의 양쪽 끝에서 발생할 수 있는 형태이다.\n• 입력이 한쪽에서만 발생하고 출력은 양쪽에서 일어날 수 있는 입력 제한과 입력은 양쪽에서 일어나고 출력은 한 곳에서만 이루어지는 출력 제한이 있다.",
        img: null,
        answers: [
            { answer_id: 237, question_id: 60, bool: false, content: " 스택", img: null },
            { answer_id: 238, question_id: 60, bool: false, content: " 큐", img: null },
            { answer_id: 239, question_id: 60, bool: false, content: " 다중 스택", img: null },
            { answer_id: 240, question_id: 60, bool: true, content: " 데크", img: null },
        ],
    },
];