export const tagColors: Record<string, string> = {
    "IT": "#FFB347",
    "에너지": "#FFDAC1",
    "미용": "#C3B299",
    "언어": "#D9BF77",
    "화학": "#F2B5D4",
    "건설": "#F2CC8F",
    "기계": "#81B29A",
    "재료": "#B5EAD7",
    "경영": "#AEC6CF",
    "디자인": "#D6AEDD",
    "제조": "#C7CEEA",
    "심리": "#BFD8B8",
    "항공": "#F4A261",
    "운송": "#FFEAA7",
    "물류": "#F7CAC9",
    "농업": "#D5AAFF",
    "보건": "#E9C46A",
    "건축": "#FAD6A5",
    "전기": "#FBC4AB",
    "문화재": "#B5838D",
    "기획": "#F5CBA7",
    "예술": "#8D99AE",
    "해양": "#A3C4BC",
    "안전": "#A8DADC",
    "측량": "#E76F51",
    "조리": "#ADD8E6",
};