name: Update main repository

on:
  push:
    branches:
      - master  # master 브랜치가 푸시될 때 실행

jobs:
  update-main-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          repository: Nea4321/YCS_Certificate  # 메인 레포
          token: ${{ secrets.PAT_TOKEN }}  # 개인 액세스 토큰 사용
          submodules: recursive  # 서브모듈 포함

      - name: Update submodules
        run: |
          git submodule update --remote --merge

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: Update submodule to latest commit" || echo "No changes to commit"
          git push origin main
